In [4]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    
    return quicksort(left) + middle + quicksort(right)

print(quicksort([2,3,1,4,5,6,1,1,19,6,7,4]))

[1, 1, 1, 2, 3, 4, 4, 5, 6, 6, 7, 19]


In [5]:
x = 3
print(type(x)) # -> <class 'int'>
print(x) # -> 3
print(x - 1) # -> 2
print(x + 1) # -> 4
print(x * 5) # -> 15 
print(x ** 2) # 3^2 = 9

x += 1
print(x) # -> 4

x *= 2
print(x) # -> 8

y = 2.5
print(type(y)) # -> <class 'fload'>
print(y, y + 1, y * 2, y ** 2) # -> 2.5, 3.5, 5.0, 6.25

# python does not have (x++) or (x--)

<class 'int'>
3
2
4
15
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [7]:
# Booleans

t = True
f = False
print(type(t)) # -> <class 'bool'>
print(t and t) # -> True
print(t or t) # -> True 
print(not t) # -> False
print(t != t) # -> False

<class 'bool'>
True
True
False
False


In [25]:
# Strings

# '' similar to ""
hello = 'hello'
world = "world"


print(hello)
print(len(hello))


hw  = hello + ' ' + world
print(hw)

# sprintf style string formatting
hw12 = '%s %s %d' %(hello, world, 12)
print(hw12)

s = 'tu nguyen'
print(s.capitalize()) # viet hoa chu cai dau -> Tu nguyen
print(s.upper()) # viet hoa ca chuoi -> TU NGUYEN
print(s.rjust(15)) # can le trai
print(s.center(15)) # can giua
print(s.replace('l', '(ell)')) # thay the 
print('   world ..   '.strip()) # loai bo khoang trang o dau va cuoi

hello
5
hello world
hello world 12
Tu nguyen
TU NGUYEN
      tu nguyen
   tu nguyen   
tu nguyen
world ..


In [37]:
#List

xs = [3, 1, 2]
print(xs, xs[2]) # [3, 1, 2] 2
print(xs[-1]) # xs[-1] = xs[-1+3] = 2 


xs[2] = 'foo'
print(xs) # -> [3, 1, 'foo']

xs.append('bar')
print(xs) # -> [3, 1, 'foo', 'bar']

x = xs.pop()
print(x, xs) # -> 'bar' [3, 1, 'foo']

print('\n\n')

nums = list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8,9]
print(nums)

print('\n')

animals = ['cat', 'dog', 'monkey']
for animal in animals: 
    print(animal)
    
print('\n')

    
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
    
print('\n')

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

# squares = [x ** 2 for x in nums]

print('\n')

even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']



[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


cat
dog
monkey


#1: cat
#2: dog
#3: monkey


[0, 1, 4, 9, 16]


[0, 4, 16]


In [41]:
# Dictionaries

d = {'cat': 'cute', 'dog': 'furry'} 

print(d['cat']) # -> cute      
print('cat' in d) # -> True (check)

d['fish'] = 'wet'     
print(d['fish'])

# print(d['monkey'])  
print(d.get('monkey', 'N/A')) 
print(d.get('fish', 'N/A'))  

del d['fish']    # remove    
print(d.get('fish', 'N/A')) 

print('\n')

d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# similar to    
#for animal, legs in d.items():
#    print('A %s has %d legs' % (animal, legs))

print('\n')

nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

cute
True
wet
N/A
wet
N/A


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


{0: 0, 2: 4, 4: 16}


In [130]:
#Sets

animals = {'cat', 'dog'}
print('cat' in animals) # check -> True
print('fish' in animals) # False

animals.add('fish')
print('fish' in animals) # -> True

print(len(animals)) # 3 

animals.add('cat') # already in the set
print(len(animals)) # -> 3

animals.remove('cat')
print(len(animals)) # 2

print('\n')

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

print('\n')
    
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums) 

True
False
True
3
3
2


#1: fish
#2: dog
#3: cat


{0, 1, 2, 3, 4, 5}


In [47]:
# Tuples
d = {(x, x + 1): x for x in range(10)}
t = (5, 6)
print(type(t))
print(d[t])
print(d[1, 2])

<class 'tuple'>
5
1


In [49]:
# Functions

def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

print('\n')

def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # -> Bob
hello('Fred', loud=True)  # -> FRED

negative
zero
positive


Hello, Bob
HELLO, FRED!


In [53]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  
        
    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  
g.greet()            
g.greet(loud=True) 

Hello, Fred
HELLO, FRED!


In [65]:
# Arrays

import numpy as np

a = np.array([1, 2, 3])
print(type(a)) # -> <class 'numpy.ndarray'
print(a.shape) # -> (3,)
print(a[0], a[1], a[2]) # 1 2 3

a[0] = 15
print(a) # [15, 2, 3]

b = np.array([[1,2,3], [4,5,6]])
print(b.shape) # (2,3)
print(b[0,0], b[0,1], b[0,2]) # 1 2 3

print('\n')

a = np.zeros((2,3))
print(a) # [[0. 0. 0.][0. 0. 0.]]

b = np.ones((2,)) 
print(b) # [1. 1.]

c = np.full((3,2), 7)
print(c) # [[7. 7.][7. 7.][7. 7.]]

<class 'numpy.ndarray'>
(3,)
1 2 3
[15  2  3]
(2, 3)
1 2 3


[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]
[[7 7]
 [7 7]
 [7 7]]


In [69]:
# Array indexing

import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]
# b = [[2 3][6 7]] || b = np.array([2,3], [6,7])

print(a)

print(a[0, 1]) # 2

# b = [[2 3][6 7]] || b = np.array([2,3], [6,7])
b[0, 0] = 77 # b = [[77 3][6 7]]
print (a[0, 1]) # 77

print('\n')

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :] # [5 6 7 8]
row_r2 = a[1:2, :] # [[5 6 7 8]]

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
77


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [83]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])
print(a[[0,1,2],[0,1,0]])
# a[0][0] = 1; a[1][1] = 4; a[2][0] = 5

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

print(a[[0,0], [1,1]])
# a[0,1] = 2; a[0,1] = 2

print(np.array([a[0,1], a[0,1]]))

print('\n')

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

print('\n')

b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])


a[np.arange(4), b] == 10

print('\n')

print(a)

[1 4 5]
[1 4 5]
[2 2]
[2 2]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[ 1  6  7 11]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [87]:
# Boolean array indexing

a = np.array([[1,2], [3, 4], [5, 6]])

book_idx = (a > 2) # ktra phan tu > 2

print(book_idx)

print(a[book_idx]) # [3 4 5 6]

print(a[a>2]) # [3 4 5 6]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [90]:
# Datatypes
import numpy as np

x = np.array([1, 2])
print(x.dtype) # -> int64

x = np.array([1.0, 2.1])
print(x.dtype) # -> float64

x = np.array([1.1, 2], dtype=np.int64)
print(x.dtype)
print(x)

int64
float64
int64
[1 2]


In [100]:
# Array math
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x,y))
# print(x + y) similar to print(np.add(x,y))

print (x - y)
print(np.subtract(x, y))
# print(x - y) similar to print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))
# print(x * y) similar to print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))
# print(x / y) similar to print(np.divide(x, y))

print(np.sqrt(x))

print('\n')

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))
# -> 9*11 + 10*12 = 219
# print(v.dot(w)) similar to print(np.dot(v, w))
# nhan 2 ma tran

print(x.dot(v))
print(np.dot(x, v))
# [1*9+2*10 3*9+4*10] = [29 67]

print(x.dot(y))
print(np.dot(x, y))
#[[19 22] [43 50]]
# nhan 2 ma tran

print('\n')

x = np.array([[1,2],[3,4]])
print(np.sum(x))
# 1+2+3+4 = 10

print(np.sum(x, axis=0))
# tong cua moi cot -> [4 6]

print(np.sum(x, axis=1))
# tong cua moi hang -> [3 7]

print('\n')

x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

print('\n')

v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


10
[4 6]
[3 7]


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


[1 2 3]
[1 2 3]


In [109]:
# Broadcasting
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # tao ma tran y giong x 

print(y)

print('\n')

for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

print('\n')

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))

print(vv)

print('\n')

y = x + vv
print(y)

print('\n')

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [3]:
import numpy as np

v = np.array([1, 2, 3])
w = np.array([4, 5])

print(np.reshape(v, (3, 1)) * w)

x = np.array([[1,2,3], [4,5,6]])
print(x + v)

print((x.T + w).T)
print(x + np.reshape(w, (2, 1)))
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [4]:
#import imageio
#---------------#

def scope_test():
    def do_local():
        spam = "local spam"

    def do_nonlocal():
        nonlocal spam
        spam = "nonlocal spam"

    def do_global():
        global spam
        spam = "global spam"

    spam = "test spam"
    do_local()
    print("After local assignment:", spam)
    do_nonlocal()
    print("After nonlocal assignment:", spam)
    do_global()
    print("After global assignment:", spam)

scope_test()
print("In global scope:", spam)

After local assignment: test spam
After nonlocal assignment: nonlocal spam
After global assignment: nonlocal spam
In global scope: global spam
